### ISSUE TITLE
 forward() missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by LittleTigger-alpha** [yxlijun/Pyramidbox.pytorch#22]
I met an error.
Traceback (most recent call last):
  File "demo.py", line 111, in <module>
    detect(net, path, args.thresh)
  File "demo.py", line 70, in detect
    y = net(x)
  File "/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

how do I fix it?

**Comment by berkanttubi** [comment]
UP , any solution please??

**Comment by mingyue474** [comment]
请问有办法了吗？

**Comment by berkanttubi** [comment]
It is about the Pytorch version I think. Pytorch 1.0.0 or less will work

**Comment by mingyue474** [comment]
> It is about the Pytorch version I think. Pytorch 1.0.0 or less will work

谢谢！
