### ISSUE TITLE
out of memory when running  wider_test.py

### ISSUE THREAD

**Issue by vadik6666** [yxlijun/Pyramidbox.pytorch#9]
Trying to run wider_test.py on validation part:
```
python wider_test.py --model ../weights/pyramidbox_5000.pth
```

but getting an error (on 0004th image?):
```
Detect 0001 th image costs 4.4119
Detect 0002 th image costs 2.4946
Detect 0003 th image costs 3.0682
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "wider_test.py", line 238, in <module>
    det0 = detect_face(net, img, shrink)
  File "wider_test.py", line 61, in detect_face
    y = net(x)
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "../pyramidbox.py", line 153, in forward
    ssh_conv3_norm = self.cpm[0](self.L2Norm3_3(lfpn0_on_conv3))
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "../pyramidbox.py", line 57, in forward
    out_residual = self.branch1(x)
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "../pyramidbox.py", line 36, in forward
    return self.bn1(x)
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "/root/miniconda3/envs/pytorch0.3.1/lib/python3.6/site-packages/torch/nn/functional.py", line 1013, in batch_norm
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58
```
My pytorch=0.3.1
I'm using GeForce GTX 1080 Ti (11178Mb). 

@yxlijun you also work with 11Gb Titan1080. Can you help to manage this memory problem?

**Comment by yxlijun** [comment]
你可以将多尺度测试的max_im_shrink缩小一点

**Comment by vadik6666** [comment]
Спасибо, что ответил по-китайски. 
Просто добавь volatile=True в строке https://github.com/yxlijun/Pyramidbox.pytorch/blob/master/tools/wider_test.py#L54
